### ISSUE TITLE
GO111MODULE=on go get -v github.com/google/ko/cmd/ko failed 

### ISSUE THREAD

**Issue by dove-young** [google/ko#175]
### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### Does this issue reproduce with the latest release?

Yes.

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build704158439=/tmp/go-build -gno-record-gcc-switches"
```
</pre></details>

### What did you do?

```
GO111MODULE=on go get -v  github.com/google/ko/cmd/ko
go: finding github.com/google/ko/cmd/ko latest
go: finding github.com/google/ko/cmd latest
get "modernc.org/strutil": found meta tag get.metaImport{Prefix:"modernc.org/strutil", VCS:"git", RepoRoot:"https://gitlab.com/cznic/strutil"} at //modernc.org/strutil?go-get=1
get "modernc.org/golex": found meta tag get.metaImport{Prefix:"modernc.org/golex", VCS:"git", RepoRoot:"https://gitlab.com/cznic/golex"} at //modernc.org/golex?go-get=1
get "modernc.org/mathutil": found meta tag get.metaImport{Prefix:"modernc.org/mathutil", VCS:"git", RepoRoot:"https://gitlab.com/cznic/mathutil"} at //modernc.org/mathutil?go-get=1
get "modernc.org/cc": found meta tag get.metaImport{Prefix:"modernc.org/cc", VCS:"git", RepoRoot:"https://gitlab.com/cznic/cc"} at //modernc.org/cc?go-get=1
get "modernc.org/xc": found meta tag get.metaImport{Prefix:"modernc.org/xc", VCS:"git", RepoRoot:"https://gitlab.com/cznic/xc"} at //modernc.org/xc?go-get=1
go get: github.com/google/ko@v0.5.1 requires
        github.com/google/go-containerregistry@v0.0.0-20200310013544-4fe717a9b4cb requires
        k8s.io/code-generator@v0.17.2 requires
        gonum.org/v1/netlib@v0.0.0-20190331212654-76723241ea4e requires
        modernc.org/cc@v1.0.0: reading modernc.org/cc/go.mod at revision v1.0.0: git fetch -f https://gitlab.com/cznic/cc refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /root/go/pkg/mod/cache/vcs/214c7c8b018f9220f253771b1476659b6c905c4196c32b80b07a212616372040: exit status 128:
        error: RPC failed; result=22, HTTP code = 404
        fatal: The remote end hung up unexpectedly

```

**Comment by dove-young** [comment]
I can install it without `GO111MODULE=on `.

**Comment by jonjohnsonjr** [comment]
I think this happens if you try to run this from within an existing go module, since it just adds it to the existing package as a dependency?

I'm not sure if the `go` command is a great way to install global binaries in a world with go modules.

It looks like that was added so that the version info works even if you're installing via `go get`: https://github.com/google/ko/issues/85

We might just need to add better instructions.

**Comment by stanleynguyen** [comment]
Seems like a problem with upstream package but I'm getting this when trying to `GO111MODULE=on go get` from outside of an existing go module

![Screenshot 2020-06-23 at 11 28 01 PM](https://user-images.githubusercontent.com/12974927/85423500-58ac2a80-b5a9-11ea-9bf6-e3ca53a55d8b.png)

Installation of latest commit (using `go get` without GOMODULE) is fine though

**Comment by matzew** [comment]
same:

```
GO111MODULE=on go get github.com/google/ko/cmd/ko
go: found github.com/google/ko/cmd/ko in github.com/google/ko v0.5.1
# github.com/google/go-containerregistry/pkg/v1/daemon
go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20200310013544-4fe717a9b4cb/pkg/v1/daemon/image.go:115:19: undefined: client.NewClientWithOpts
go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20200310013544-4fe717a9b4cb/pkg/v1/daemon/image.go:115:44: undefined: client.FromEnv
go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20200310013544-4fe717a9b4cb/pkg/v1/daemon/write.go:38:14: undefined: client.NewClientWithOpts
go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20200310013544-4fe717a9b4cb/pkg/v1/daemon/write.go:38:39: undefined: client.FromEnv
# k8s.io/cli-runtime/pkg/resource
go/pkg/mod/k8s.io/cli-runtime@v0.17.3/pkg/resource/scheme.go:64:34: undefined: "k8s.io/apimachinery/pkg/runtime".Identifier
go/pkg/mod/k8s.io/cli-runtime@v0.17.3/pkg/resource/scheme.go:65:44: unstructured.UnstructuredJSONScheme.Identifier undefined (type "k8s.io/apimachinery/pkg/runtime".Codec has no field or method Identifier)
➜  ~ ko version
v0.2.0

```

**Comment by matzew** [comment]
OK, it worked after doing ` cd $GOROOT`

and than running:

```shell
GO111MODULE=on go get github.com/google/ko/cmd/ko
```

:man_shrugging:

**Comment by jinglundong** [comment]
Please let me know if this approach works. I fixed a similar installation problem by:
1) Create and go to a local directory that is not in the GOPATH. (GOPATH can be looked up by `go env GOPATH`)
2) GO111MODULE=off go get github.com/google/ko/cmd/ko (It has GO111MODULE=off. The behavior of Go modules differs depending on whether you are developing inside or outside of GOPATH.) 
3) export PATH=$GOPATH/bin:$PATH if not already set.

**Comment by aavarghese** [comment]
I tried ALL of the suggestions in the previous comments. I still can't get ko installed.

I get `-bash: ko: command not found`. Any ideas?
My go version is
go version go1.15 darwin/amd64

**Comment by stanleynguyen** [comment]
> I tried ALL of the suggestions in the previous comments. I still can't get ko installed.
> 
> I get `-bash: ko: command not found`. Any ideas?
> My go version is
> go version go1.15 darwin/amd64

@aavarghese Is `$GOPATH/bin` inside your `$PATH`?

**Comment by aavarghese** [comment]
@stanleynguyen thanks for the response. So finally fixed it yesterday. My $PATH had $GOPATH/bin, but my issues was that my $GOBIN was set to the wrong directory (which wasn't in $PATH). KO works for me after fixing that env var.
